### ISSUE TITLE
MDAL does not recognise UGRID from Deltares as a valid source

### ISSUE THREAD

**Issue by RobinRW** [lutraconsulting/MDAL#81] opened 2019-01-17 13:04 UTC
When trying to import a .nc file created by dFlow, by Deltares, it failes to recognise the source

**Comment by saberraz** [comment] 2019-01-17 14:07
Hi @RobinRW thanks for raising the issue. I think it is duplicate of #32 
Best to ask @Deltares if they plan to support their format? We had it in older versions of Crayfish but not in MDAL any more (due to lack of interest from @deltares)

**Closed** 2019-01-21 08:53 UTC
Labels: duplicate, enhancement, formats
